export const MEDICAL_CONDITIONS = [
  'High Blood Pressure',
  'Heart Disease',
  'Diabetes',
  'Asthma',
  'Thyroid Disease',
  'Epilepsy / Seizures',
  'Hepatitis',
  'HIV / AIDS',
  'Cancer',
  'Bleeding Disorder',
  'Anemia',
  'Arthritis',
  'Osteoporosis',
  'Kidney Disease',
  'Liver Disease',
  'Stomach / Intestinal Disease',
  'Mental Health Disorder',
  'Respiratory Problems',
  'Tuberculosis',
  'Sexually Transmitted Disease',
  'Joint Replacement',
  'Pacemaker',
  'Organ Transplant',
  'Substance Abuse History',
  'Pregnant or Nursing',
];
